dr-Ariawan-s-Project/api-drariawan

- app/config/constants.go
- features/questionaire/data/model.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/handler/handler.go
- features/questionaire/service/logic.go
- go.mod
- utils/helpers/error-handler.go
- utils/helpers/error-query.go
- utils/helpers/response.go
Ref: #2 
- create skeleton project
> refactor: add skeleton project

- features/users/entity.go
- features/users/service/logic.go
Create entity and service layer logic, fixed issue #4
> User Entity and Service Layer

- .github/workflows/deploy.yaml
- .gitignore
- Dockerfile
Ref: #13 
- add dockerfile
- setup cd and secret key github action
> feat: setup cd and Dockerfile

- migration/20230907085032_create_table_patient.down.sql
- migration/20230907085032_create_table_patient.up.sql
- migration/20230907085058_create_table_test_attempt.down.sql
- migration/20230907085058_create_table_test_attempt.up.sql
- migration/20230907085109_create_table_answer.down.sql
- migration/20230907085109_create_table_answer.up.sql
create sql migration for table `patients`, `test_attempt`, `answers`
> feat(migrate): create table patients, test_attempt, answers

- features/questionaire/data/model.go
- features/questionaire/data/query.go
* Add struct  model `TestAttempt`, `Answer` for mapping table test_attempt and answer
* Add method `InsertAnswer` to insert answer data to db
Ref: #28
> feat(answer): add query InsertAnswer

- app/router/router.go
- features/questionaire/factory/factory.go
- features/questionaire/handler/handler.go
- features/questionaire/handler/request.go
- main.go
* Add struct request AnswerRequest
```
{
"code_attempt":"dFL1UYyVMGuVBJeIuuCoICkqeeanN8NKFT459RojjXCWVVDLyQ==",
"answer":[
{
"question_id": 1,
"description": "tidak",
"score":10
},
{
"question_id": 2,
"description": "ya",
"score":1
}
]
}
```
* Add func Handler `AddAnswer`
* Change factory, add config at service layer
* Add endpoint `POST` `questioner`
Ref: #29
> feat(answer): add func post answer handler

- .github/workflows/deploy.yaml
* fixing folder name in server
* add env variable for aes-gcm secret
fix issue: #32
> fix(cicd): change folder name and add env

- features/patient/data/model.go
- features/patient/data/query.go
* add struct gorm model for patient data
* add query for patient feature
Fix issue: #35
> feat(patient): add data layer patient

- app/router/router.go
- features/patient/factory/factory.go
- features/patient/handler/handler.go
- features/patient/handler/request.go
- features/patient/handler/response.go
* add handler layer
* add request and response json format
* add route for /patients
Fix issue : #36
> feat(patient): add handler layer, add route for /patients

- app/config/constants.go
- app/router/router.go
- features/questionaire/data/model.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/factory/factory.go
- features/questionaire/handler/handler.go
- features/questionaire/handler/request.go
- features/questionaire/service/logic.go
* add validate func to start questioner
* if patient already taken the test, system will ask the user to fill as partner data.
* 1 patient just only have 1 partner
* if validation success, system will generate code attempt to start question.
Fix issue: #44
> feat(questioner): add validate to start questioner

- app/middlewares/jwt-middleware.go
* change version jwt library to v5 
`github.com/golang-jwt/jwt/v5`
Hot fix issue: #55
> fix(auth): change version jwt library to v5

- main.go
change port main.go from `8000` to `80`
Hot fix issue: #57
> fix: change port main.go

- .github/workflows/deploy.yaml
- README.md
- app/config/config.go
- features/questionaire/service/logic.go
- utils/helpers/sendEmail.go
* feature Send email questioner link.
* update readme for documentation to setup this project.
Fix Issue: #53
> feat(questioner): send email link questioner

- app/config/constants.go
- app/router/router.go
- features/users/entity.go
- features/users/handler/handler.go
- features/users/service/logic.go
- go.mod
- go.sum
- utils/validation/uservalidate.go
- Penambahan Const untuk "admin"
- penambahan variable USEJWT untuk reusable "echojwt.WithConfig(echojwt.Config{SigningMethod: "HS256", SigningKey: []byte(config.InitConfig().JWT_SECRET)})" di router
-perbaikan response error sesuai di config const pada logic user
> Revuservalidation

- app/config/constants.go
- features/schedule/data/model.go
- features/schedule/data/query.go
- features/schedule/entity.go
- features/schedule/service/logic.go
- utils/validation/schedulevalidate.go
- memperbaiki log.println yang lupa dihapus
- menambahkan const pesan error yang dibutuhkan nantinya
- mengubah pesan error yang masih manual di schedule validation helper
> Revschedulevalidation

- features/questionaire/data/model.go
- features/questionaire/entity.go
- features/questionaire/handler/response.go
restructuring get all question response
add `section`, `description`, `url_video`
Fix: #74
> fix: restructuring get all question response

- app/config/constants.go
- app/router/router.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/handler/handler.go
- features/questionaire/handler/response.go
- features/questionaire/service/logic.go
- mocks/QuestionaireData.go
`GET` `/v1/dashboard`
- berapa jumlah quistioner
- berapa jumlah quistioner yang baru (bulan ini)
- berapa jumlah quistioner yang belum di assessment
Fix: #78
> feat: add endpoint dashboard

- .gitignore
- app/config/constants.go
- features/questionaire/data/model.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/service/logic.go
- features/questionaire/service/logic_test.go
- mocks/QuestionaireData.go
- utils/helpers/handler-code.go
- POST /questioner validation saat pasien menjawab pertanyaan. seluruh jawabannya harus sama jumlahnya dengan banyaknya pertanyaan.
- POST /questioner/validate validation untuk check jika sudah sempat request code attempt tapi belum pernah menginputkan jawaban. maka kirim ulang code attempt ke email
Fix: #76
> PR: validate attempt questioner and check total answer

- app/config/constants.go
- app/router/router.go
- features/dashboard/data/model.go
- features/dashboard/data/query.go
- features/dashboard/entity.go
- features/dashboard/factory/factory.go
- features/dashboard/handler/handler.go
- features/dashboard/handler/response.go
- features/dashboard/service/logic.go
- features/patient/data/query.go
- features/patient/entity.go
- features/patient/service/logic.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/factory/factory.go
- features/questionaire/handler/handler.go
- features/questionaire/service/logic.go
- mocks/PatientService.go
Refactor dashboard. put on new features folder
and add some data:
- GET `/dashboard` 'Add count patient in response
- GET `/dashboard/questioner` count test attempt per month for chart
Fix: #81
> feat(dashboard): refactor and add count patient

- migration/20231020161705_alter_testattempt_ai_diagnosis.down.sql
- migration/20231020161705_alter_testattempt_ai_diagnosis.up.sql
table `test_attempt`
change type `ai_diagnosis` from float to text
Fix: #86
> fix(test_attempt): change ai_diagnosis from float to text

- app/config/constants.go
- app/router/router.go
- features/patient/handler/handler.go
- utils/helpers/handler-code.go
GET `/patients/profile`
Fix: #83
> feat(patient): profile patient

- app/router/router.go
- features/questionaire/data/model.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/handler/handler.go
- features/questionaire/handler/response.go
- features/questionaire/service/logic.go
- mocks/QuestionaireData.go
GET `/questioner/attempt/list`
Fix: #85
> feat(questioner): add list questioner attempt

- features/booking/service/logic.go
menambahkan patient role agar bisa booking jadwal dokter
Fix: #96
> fix(booking): add patient role to create booking

- app/router/router.go
- features/users/handler/handler.go
add middleware jwt claim at some endpoints
Fix: #98
> fix(jwt): add middleware jwt to some endpoints

- app/router/router.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/handler/handler.go
- features/questionaire/handler/request.go
- features/questionaire/service/logic.go
add endpoint 
POST `/v1/questioner/attempts/:attempt_id/assesments`
Fix: #94
> feat(questioner): add assesment approval

- features/patient/data/query.go
- features/patient/entity.go
- features/patient/service/logic.go
- mocks/QuestionaireData.go
add duplicate nik validation when add patient and update data patient
Fix: #101
> fix: add duplicate NIK validation

- utils/validation/uservalidate.go
- remove alpha and alphanum tags on users struct
- change tag minimum password length from 3 to 5 where update users
Fix: #111
> fix(users): change users validation, remove alpha tags

- features/booking/service/logic.go
- features/schedule/service/logic.go
- features/users/service/logic.go
change constant `InvalidValidationAccess` to `Unauthorized`
Fix: #113
> fix: change constant InvalidValidationAccess to Unauthorized

- features/users/data/query.go
- features/users/handler/handler.go
- features/users/service/logic.go
fix get user list when there is new request without queryparam
> fix: user list without queryparam

- features/users/data/query.go
- features/users/entity.go
- features/users/handler/handler.go
- features/users/service/logic.go
Fix: #131 
add query param `role` to `/user/list`
> feat: add query param role to get all users

- features/patient/data/query.go
- features/users/data/query.go
Fix: #133 
add where clause deleted_at in func pagination counter
> fix: add where clause deleted_at at count func

- app/router/router.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/handler/handler.go
- features/questionaire/service/logic.go
- mocks/QuestionaireData.go
Fix: #146 
add endpoint 
`/v1/questioner/attempts/:attempt_id`
> feat(questionaire): get detail questionaire attempt by id attempt

- app/config/constants.go
- features/dashboard/service/logic.go
- features/questionaire/data/query.go
- features/questionaire/entity.go
- features/questionaire/service/logic.go
- mocks/QuestionaireData.go
- utils/helpers/sendEmail.go
Fix: #148  
* check code attempt valid or not
* update url questionnaire
> [Fix] check code attempt and set url questionnaire

- features/patient/service/logic.go
Fix: #155 
add validation check when password is empty or not when add/register patient
> fix: add check password is empty when add patient

- utils/files/assessment-result.html
> Add Template for Assessment Result

- app/config/constants.go
- app/router/router.go
- features/booking/data/query.go
- features/booking/entity.go
- features/booking/handler/handler.go
- features/booking/service/logic.go
Fix: #158 
add endpoint cancel booking for suster
* `POST` `/booking/{bookingid}/cancel`
> Add cancel booking for suster
